/* This file was generated by SableCC (http://www.sablecc.org/). */

package fr.umlv.symphonie.data.formula.node;

import fr.umlv.symphonie.data.formula.analysis.Analysis;

public final class AAdditionAdditiveExpression extends PAdditiveExpression {

  private PAdditiveExpression _left_;
  private TAdditionOperator _additionOperator_;
  private PMultiplicativeExpression _right_;

  public AAdditionAdditiveExpression() {
  }

  public AAdditionAdditiveExpression(PAdditiveExpression _left_,
      TAdditionOperator _additionOperator_, PMultiplicativeExpression _right_) {
    setLeft(_left_);

    setAdditionOperator(_additionOperator_);

    setRight(_right_);

  }

  public Object clone() {
    return new AAdditionAdditiveExpression(
        (PAdditiveExpression) cloneNode(_left_),
        (TAdditionOperator) cloneNode(_additionOperator_),
        (PMultiplicativeExpression) cloneNode(_right_));
  }

  public void apply(Switch sw) {
    ((Analysis) sw).caseAAdditionAdditiveExpression(this);
  }

  public PAdditiveExpression getLeft() {
    return _left_;
  }

  public void setLeft(PAdditiveExpression node) {
    if (_left_ != null) {
      _left_.parent(null);
    }

    if (node != null) {
      if (node.parent() != null) {
        node.parent().removeChild(node);
      }

      node.parent(this);
    }

    _left_ = node;
  }

  public TAdditionOperator getAdditionOperator() {
    return _additionOperator_;
  }

  public void setAdditionOperator(TAdditionOperator node) {
    if (_additionOperator_ != null) {
      _additionOperator_.parent(null);
    }

    if (node != null) {
      if (node.parent() != null) {
        node.parent().removeChild(node);
      }

      node.parent(this);
    }

    _additionOperator_ = node;
  }

  public PMultiplicativeExpression getRight() {
    return _right_;
  }

  public void setRight(PMultiplicativeExpression node) {
    if (_right_ != null) {
      _right_.parent(null);
    }

    if (node != null) {
      if (node.parent() != null) {
        node.parent().removeChild(node);
      }

      node.parent(this);
    }

    _right_ = node;
  }

  public String toString() {
    return "" + toString(_left_) + toString(_additionOperator_)
        + toString(_right_);
  }

  void removeChild(Node child) {
    if (_left_ == child) {
      _left_ = null;
      return;
    }

    if (_additionOperator_ == child) {
      _additionOperator_ = null;
      return;
    }

    if (_right_ == child) {
      _right_ = null;
      return;
    }

  }

  void replaceChild(Node oldChild, Node newChild) {
    if (_left_ == oldChild) {
      setLeft((PAdditiveExpression) newChild);
      return;
    }

    if (_additionOperator_ == oldChild) {
      setAdditionOperator((TAdditionOperator) newChild);
      return;
    }

    if (_right_ == oldChild) {
      setRight((PMultiplicativeExpression) newChild);
      return;
    }

  }
}
