/* This file was generated by SableCC (http://www.sablecc.org/). */

package fr.umlv.symphonie.data.formula.node;

import fr.umlv.symphonie.data.formula.analysis.Analysis;

public final class ADataBlockExpression extends PBlockExpression {

  private TBlockPrefix _blockPrefix_;
  private TFuncId _funcId_;

  public ADataBlockExpression() {
  }

  public ADataBlockExpression(TBlockPrefix _blockPrefix_, TFuncId _funcId_) {
    setBlockPrefix(_blockPrefix_);

    setFuncId(_funcId_);

  }

  public Object clone() {
    return new ADataBlockExpression((TBlockPrefix) cloneNode(_blockPrefix_),
        (TFuncId) cloneNode(_funcId_));
  }

  public void apply(Switch sw) {
    ((Analysis) sw).caseADataBlockExpression(this);
  }

  public TBlockPrefix getBlockPrefix() {
    return _blockPrefix_;
  }

  public void setBlockPrefix(TBlockPrefix node) {
    if (_blockPrefix_ != null) {
      _blockPrefix_.parent(null);
    }

    if (node != null) {
      if (node.parent() != null) {
        node.parent().removeChild(node);
      }

      node.parent(this);
    }

    _blockPrefix_ = node;
  }

  public TFuncId getFuncId() {
    return _funcId_;
  }

  public void setFuncId(TFuncId node) {
    if (_funcId_ != null) {
      _funcId_.parent(null);
    }

    if (node != null) {
      if (node.parent() != null) {
        node.parent().removeChild(node);
      }

      node.parent(this);
    }

    _funcId_ = node;
  }

  public String toString() {
    return "" + toString(_blockPrefix_) + toString(_funcId_);
  }

  void removeChild(Node child) {
    if (_blockPrefix_ == child) {
      _blockPrefix_ = null;
      return;
    }

    if (_funcId_ == child) {
      _funcId_ = null;
      return;
    }

  }

  void replaceChild(Node oldChild, Node newChild) {
    if (_blockPrefix_ == oldChild) {
      setBlockPrefix((TBlockPrefix) newChild);
      return;
    }

    if (_funcId_ == oldChild) {
      setFuncId((TFuncId) newChild);
      return;
    }

  }
}
