/* This file was generated by SableCC (http://www.sablecc.org/). */

package fr.umlv.symphonie.data.formula.node;

import fr.umlv.symphonie.data.formula.analysis.Analysis;

public final class AGreaterThanRelationalExpression extends
    PRelationalExpression {

  private PAdditiveExpression _left_;
  private TGreaterThan _greaterThan_;
  private PAdditiveExpression _right_;

  public AGreaterThanRelationalExpression() {
  }

  public AGreaterThanRelationalExpression(PAdditiveExpression _left_,
      TGreaterThan _greaterThan_, PAdditiveExpression _right_) {
    setLeft(_left_);

    setGreaterThan(_greaterThan_);

    setRight(_right_);

  }

  public Object clone() {
    return new AGreaterThanRelationalExpression(
        (PAdditiveExpression) cloneNode(_left_),
        (TGreaterThan) cloneNode(_greaterThan_),
        (PAdditiveExpression) cloneNode(_right_));
  }

  public void apply(Switch sw) {
    ((Analysis) sw).caseAGreaterThanRelationalExpression(this);
  }

  public PAdditiveExpression getLeft() {
    return _left_;
  }

  public void setLeft(PAdditiveExpression node) {
    if (_left_ != null) {
      _left_.parent(null);
    }

    if (node != null) {
      if (node.parent() != null) {
        node.parent().removeChild(node);
      }

      node.parent(this);
    }

    _left_ = node;
  }

  public TGreaterThan getGreaterThan() {
    return _greaterThan_;
  }

  public void setGreaterThan(TGreaterThan node) {
    if (_greaterThan_ != null) {
      _greaterThan_.parent(null);
    }

    if (node != null) {
      if (node.parent() != null) {
        node.parent().removeChild(node);
      }

      node.parent(this);
    }

    _greaterThan_ = node;
  }

  public PAdditiveExpression getRight() {
    return _right_;
  }

  public void setRight(PAdditiveExpression node) {
    if (_right_ != null) {
      _right_.parent(null);
    }

    if (node != null) {
      if (node.parent() != null) {
        node.parent().removeChild(node);
      }

      node.parent(this);
    }

    _right_ = node;
  }

  public String toString() {
    return "" + toString(_left_) + toString(_greaterThan_) + toString(_right_);
  }

  void removeChild(Node child) {
    if (_left_ == child) {
      _left_ = null;
      return;
    }

    if (_greaterThan_ == child) {
      _greaterThan_ = null;
      return;
    }

    if (_right_ == child) {
      _right_ = null;
      return;
    }

  }

  void replaceChild(Node oldChild, Node newChild) {
    if (_left_ == oldChild) {
      setLeft((PAdditiveExpression) newChild);
      return;
    }

    if (_greaterThan_ == oldChild) {
      setGreaterThan((TGreaterThan) newChild);
      return;
    }

    if (_right_ == oldChild) {
      setRight((PAdditiveExpression) newChild);
      return;
    }

  }
}
