/* This file was generated by SableCC (http://www.sablecc.org/). */

package fr.umlv.symphonie.data.formula.node;

import fr.umlv.symphonie.data.formula.analysis.Analysis;

public final class ALessThanRelationalExpression extends PRelationalExpression {

  private PAdditiveExpression _left_;
  private TLessThan _lessThan_;
  private PAdditiveExpression _right_;

  public ALessThanRelationalExpression() {
  }

  public ALessThanRelationalExpression(PAdditiveExpression _left_,
      TLessThan _lessThan_, PAdditiveExpression _right_) {
    setLeft(_left_);

    setLessThan(_lessThan_);

    setRight(_right_);

  }

  public Object clone() {
    return new ALessThanRelationalExpression(
        (PAdditiveExpression) cloneNode(_left_),
        (TLessThan) cloneNode(_lessThan_),
        (PAdditiveExpression) cloneNode(_right_));
  }

  public void apply(Switch sw) {
    ((Analysis) sw).caseALessThanRelationalExpression(this);
  }

  public PAdditiveExpression getLeft() {
    return _left_;
  }

  public void setLeft(PAdditiveExpression node) {
    if (_left_ != null) {
      _left_.parent(null);
    }

    if (node != null) {
      if (node.parent() != null) {
        node.parent().removeChild(node);
      }

      node.parent(this);
    }

    _left_ = node;
  }

  public TLessThan getLessThan() {
    return _lessThan_;
  }

  public void setLessThan(TLessThan node) {
    if (_lessThan_ != null) {
      _lessThan_.parent(null);
    }

    if (node != null) {
      if (node.parent() != null) {
        node.parent().removeChild(node);
      }

      node.parent(this);
    }

    _lessThan_ = node;
  }

  public PAdditiveExpression getRight() {
    return _right_;
  }

  public void setRight(PAdditiveExpression node) {
    if (_right_ != null) {
      _right_.parent(null);
    }

    if (node != null) {
      if (node.parent() != null) {
        node.parent().removeChild(node);
      }

      node.parent(this);
    }

    _right_ = node;
  }

  public String toString() {
    return "" + toString(_left_) + toString(_lessThan_) + toString(_right_);
  }

  void removeChild(Node child) {
    if (_left_ == child) {
      _left_ = null;
      return;
    }

    if (_lessThan_ == child) {
      _lessThan_ = null;
      return;
    }

    if (_right_ == child) {
      _right_ = null;
      return;
    }

  }

  void replaceChild(Node oldChild, Node newChild) {
    if (_left_ == oldChild) {
      setLeft((PAdditiveExpression) newChild);
      return;
    }

    if (_lessThan_ == oldChild) {
      setLessThan((TLessThan) newChild);
      return;
    }

    if (_right_ == oldChild) {
      setRight((PAdditiveExpression) newChild);
      return;
    }

  }
}
