/* This file was generated by SableCC (http://www.sablecc.org/). */

package fr.umlv.symphonie.data.formula.node;

import fr.umlv.symphonie.data.formula.analysis.Analysis;

public final class ALessThanOrEqualsRelationalExpression extends
    PRelationalExpression {

  private PAdditiveExpression _left_;
  private TLessThanOrEquals _lessThanOrEquals_;
  private PAdditiveExpression _right_;

  public ALessThanOrEqualsRelationalExpression() {
  }

  public ALessThanOrEqualsRelationalExpression(PAdditiveExpression _left_,
      TLessThanOrEquals _lessThanOrEquals_, PAdditiveExpression _right_) {
    setLeft(_left_);

    setLessThanOrEquals(_lessThanOrEquals_);

    setRight(_right_);

  }

  public Object clone() {
    return new ALessThanOrEqualsRelationalExpression(
        (PAdditiveExpression) cloneNode(_left_),
        (TLessThanOrEquals) cloneNode(_lessThanOrEquals_),
        (PAdditiveExpression) cloneNode(_right_));
  }

  public void apply(Switch sw) {
    ((Analysis) sw).caseALessThanOrEqualsRelationalExpression(this);
  }

  public PAdditiveExpression getLeft() {
    return _left_;
  }

  public void setLeft(PAdditiveExpression node) {
    if (_left_ != null) {
      _left_.parent(null);
    }

    if (node != null) {
      if (node.parent() != null) {
        node.parent().removeChild(node);
      }

      node.parent(this);
    }

    _left_ = node;
  }

  public TLessThanOrEquals getLessThanOrEquals() {
    return _lessThanOrEquals_;
  }

  public void setLessThanOrEquals(TLessThanOrEquals node) {
    if (_lessThanOrEquals_ != null) {
      _lessThanOrEquals_.parent(null);
    }

    if (node != null) {
      if (node.parent() != null) {
        node.parent().removeChild(node);
      }

      node.parent(this);
    }

    _lessThanOrEquals_ = node;
  }

  public PAdditiveExpression getRight() {
    return _right_;
  }

  public void setRight(PAdditiveExpression node) {
    if (_right_ != null) {
      _right_.parent(null);
    }

    if (node != null) {
      if (node.parent() != null) {
        node.parent().removeChild(node);
      }

      node.parent(this);
    }

    _right_ = node;
  }

  public String toString() {
    return "" + toString(_left_) + toString(_lessThanOrEquals_)
        + toString(_right_);
  }

  void removeChild(Node child) {
    if (_left_ == child) {
      _left_ = null;
      return;
    }

    if (_lessThanOrEquals_ == child) {
      _lessThanOrEquals_ = null;
      return;
    }

    if (_right_ == child) {
      _right_ = null;
      return;
    }

  }

  void replaceChild(Node oldChild, Node newChild) {
    if (_left_ == oldChild) {
      setLeft((PAdditiveExpression) newChild);
      return;
    }

    if (_lessThanOrEquals_ == oldChild) {
      setLessThanOrEquals((TLessThanOrEquals) newChild);
      return;
    }

    if (_right_ == oldChild) {
      setRight((PAdditiveExpression) newChild);
      return;
    }

  }
}
