/* This file was generated by SableCC (http://www.sablecc.org/). */

package fr.umlv.symphonie.data.formula.node;

import fr.umlv.symphonie.data.formula.analysis.Analysis;

public final class AMinusUnaryExpression extends PUnaryExpression {

  private TSubstractionOperator _substractionOperator_;
  private PNumericExpression _numericExpression_;

  public AMinusUnaryExpression() {
  }

  public AMinusUnaryExpression(TSubstractionOperator _substractionOperator_,
      PNumericExpression _numericExpression_) {
    setSubstractionOperator(_substractionOperator_);

    setNumericExpression(_numericExpression_);

  }

  public Object clone() {
    return new AMinusUnaryExpression(
        (TSubstractionOperator) cloneNode(_substractionOperator_),
        (PNumericExpression) cloneNode(_numericExpression_));
  }

  public void apply(Switch sw) {
    ((Analysis) sw).caseAMinusUnaryExpression(this);
  }

  public TSubstractionOperator getSubstractionOperator() {
    return _substractionOperator_;
  }

  public void setSubstractionOperator(TSubstractionOperator node) {
    if (_substractionOperator_ != null) {
      _substractionOperator_.parent(null);
    }

    if (node != null) {
      if (node.parent() != null) {
        node.parent().removeChild(node);
      }

      node.parent(this);
    }

    _substractionOperator_ = node;
  }

  public PNumericExpression getNumericExpression() {
    return _numericExpression_;
  }

  public void setNumericExpression(PNumericExpression node) {
    if (_numericExpression_ != null) {
      _numericExpression_.parent(null);
    }

    if (node != null) {
      if (node.parent() != null) {
        node.parent().removeChild(node);
      }

      node.parent(this);
    }

    _numericExpression_ = node;
  }

  public String toString() {
    return "" + toString(_substractionOperator_)
        + toString(_numericExpression_);
  }

  void removeChild(Node child) {
    if (_substractionOperator_ == child) {
      _substractionOperator_ = null;
      return;
    }

    if (_numericExpression_ == child) {
      _numericExpression_ = null;
      return;
    }

  }

  void replaceChild(Node oldChild, Node newChild) {
    if (_substractionOperator_ == oldChild) {
      setSubstractionOperator((TSubstractionOperator) newChild);
      return;
    }

    if (_numericExpression_ == oldChild) {
      setNumericExpression((PNumericExpression) newChild);
      return;
    }

  }
}
