/* This file was generated by SableCC (http://www.sablecc.org/). */

package fr.umlv.symphonie.data.formula.node;

import fr.umlv.symphonie.data.formula.analysis.Analysis;

public final class AParentheticNumericExpression extends PNumericExpression {

  private TLeftParenthesis _leftParenthesis_;
  private PAdditiveExpression _additiveExpression_;
  private TRightParenthesis _rightParenthesis_;

  public AParentheticNumericExpression() {
  }

  public AParentheticNumericExpression(TLeftParenthesis _leftParenthesis_,
      PAdditiveExpression _additiveExpression_,
      TRightParenthesis _rightParenthesis_) {
    setLeftParenthesis(_leftParenthesis_);

    setAdditiveExpression(_additiveExpression_);

    setRightParenthesis(_rightParenthesis_);

  }

  public Object clone() {
    return new AParentheticNumericExpression(
        (TLeftParenthesis) cloneNode(_leftParenthesis_),
        (PAdditiveExpression) cloneNode(_additiveExpression_),
        (TRightParenthesis) cloneNode(_rightParenthesis_));
  }

  public void apply(Switch sw) {
    ((Analysis) sw).caseAParentheticNumericExpression(this);
  }

  public TLeftParenthesis getLeftParenthesis() {
    return _leftParenthesis_;
  }

  public void setLeftParenthesis(TLeftParenthesis node) {
    if (_leftParenthesis_ != null) {
      _leftParenthesis_.parent(null);
    }

    if (node != null) {
      if (node.parent() != null) {
        node.parent().removeChild(node);
      }

      node.parent(this);
    }

    _leftParenthesis_ = node;
  }

  public PAdditiveExpression getAdditiveExpression() {
    return _additiveExpression_;
  }

  public void setAdditiveExpression(PAdditiveExpression node) {
    if (_additiveExpression_ != null) {
      _additiveExpression_.parent(null);
    }

    if (node != null) {
      if (node.parent() != null) {
        node.parent().removeChild(node);
      }

      node.parent(this);
    }

    _additiveExpression_ = node;
  }

  public TRightParenthesis getRightParenthesis() {
    return _rightParenthesis_;
  }

  public void setRightParenthesis(TRightParenthesis node) {
    if (_rightParenthesis_ != null) {
      _rightParenthesis_.parent(null);
    }

    if (node != null) {
      if (node.parent() != null) {
        node.parent().removeChild(node);
      }

      node.parent(this);
    }

    _rightParenthesis_ = node;
  }

  public String toString() {
    return "" + toString(_leftParenthesis_) + toString(_additiveExpression_)
        + toString(_rightParenthesis_);
  }

  void removeChild(Node child) {
    if (_leftParenthesis_ == child) {
      _leftParenthesis_ = null;
      return;
    }

    if (_additiveExpression_ == child) {
      _additiveExpression_ = null;
      return;
    }

    if (_rightParenthesis_ == child) {
      _rightParenthesis_ = null;
      return;
    }

  }

  void replaceChild(Node oldChild, Node newChild) {
    if (_leftParenthesis_ == oldChild) {
      setLeftParenthesis((TLeftParenthesis) newChild);
      return;
    }

    if (_additiveExpression_ == oldChild) {
      setAdditiveExpression((PAdditiveExpression) newChild);
      return;
    }

    if (_rightParenthesis_ == oldChild) {
      setRightParenthesis((TRightParenthesis) newChild);
      return;
    }

  }
}
