/* This file was generated by SableCC (http://www.sablecc.org/). */

package fr.umlv.symphonie.data.formula.node;

import fr.umlv.symphonie.data.formula.analysis.Analysis;

public final class ASubstractionAdditiveExpression extends PAdditiveExpression {

  private PAdditiveExpression _left_;
  private TSubstractionOperator _substractionOperator_;
  private PMultiplicativeExpression _right_;

  public ASubstractionAdditiveExpression() {
  }

  public ASubstractionAdditiveExpression(PAdditiveExpression _left_,
      TSubstractionOperator _substractionOperator_,
      PMultiplicativeExpression _right_) {
    setLeft(_left_);

    setSubstractionOperator(_substractionOperator_);

    setRight(_right_);

  }

  public Object clone() {
    return new ASubstractionAdditiveExpression(
        (PAdditiveExpression) cloneNode(_left_),
        (TSubstractionOperator) cloneNode(_substractionOperator_),
        (PMultiplicativeExpression) cloneNode(_right_));
  }

  public void apply(Switch sw) {
    ((Analysis) sw).caseASubstractionAdditiveExpression(this);
  }

  public PAdditiveExpression getLeft() {
    return _left_;
  }

  public void setLeft(PAdditiveExpression node) {
    if (_left_ != null) {
      _left_.parent(null);
    }

    if (node != null) {
      if (node.parent() != null) {
        node.parent().removeChild(node);
      }

      node.parent(this);
    }

    _left_ = node;
  }

  public TSubstractionOperator getSubstractionOperator() {
    return _substractionOperator_;
  }

  public void setSubstractionOperator(TSubstractionOperator node) {
    if (_substractionOperator_ != null) {
      _substractionOperator_.parent(null);
    }

    if (node != null) {
      if (node.parent() != null) {
        node.parent().removeChild(node);
      }

      node.parent(this);
    }

    _substractionOperator_ = node;
  }

  public PMultiplicativeExpression getRight() {
    return _right_;
  }

  public void setRight(PMultiplicativeExpression node) {
    if (_right_ != null) {
      _right_.parent(null);
    }

    if (node != null) {
      if (node.parent() != null) {
        node.parent().removeChild(node);
      }

      node.parent(this);
    }

    _right_ = node;
  }

  public String toString() {
    return "" + toString(_left_) + toString(_substractionOperator_)
        + toString(_right_);
  }

  void removeChild(Node child) {
    if (_left_ == child) {
      _left_ = null;
      return;
    }

    if (_substractionOperator_ == child) {
      _substractionOperator_ = null;
      return;
    }

    if (_right_ == child) {
      _right_ = null;
      return;
    }

  }

  void replaceChild(Node oldChild, Node newChild) {
    if (_left_ == oldChild) {
      setLeft((PAdditiveExpression) newChild);
      return;
    }

    if (_substractionOperator_ == oldChild) {
      setSubstractionOperator((TSubstractionOperator) newChild);
      return;
    }

    if (_right_ == oldChild) {
      setRight((PMultiplicativeExpression) newChild);
      return;
    }

  }
}
