/* This file was generated by SableCC (http://www.sablecc.org/). */

package fr.umlv.symphonie.data.formula.node;

public class NodeCast implements Cast {

  public final static NodeCast instance = new NodeCast();

  private NodeCast() {
  }

  public Object cast(Object o) {
    return (Node) o;
  }
}
