/* This file was generated by SableCC (http://www.sablecc.org/). */

package fr.umlv.symphonie.data.formula.node;

import fr.umlv.symphonie.data.formula.analysis.Analysis;

public final class TBlockEnd extends Token {

  public TBlockEnd() {
    super.setText("}");
  }

  public TBlockEnd(int line, int pos) {
    super.setText("}");
    setLine(line);
    setPos(pos);
  }

  public Object clone() {
    return new TBlockEnd(getLine(), getPos());
  }

  public void apply(Switch sw) {
    ((Analysis) sw).caseTBlockEnd(this);
  }

  public void setText(String text) {
    throw new RuntimeException("Cannot change TBlockEnd text.");
  }
}
