/* This file was generated by SableCC (http://www.sablecc.org/). */

package fr.umlv.symphonie.data.formula.node;

import fr.umlv.symphonie.data.formula.analysis.Analysis;

public final class TBlockStart extends Token {

  public TBlockStart() {
    super.setText("${");
  }

  public TBlockStart(int line, int pos) {
    super.setText("${");
    setLine(line);
    setPos(pos);
  }

  public Object clone() {
    return new TBlockStart(getLine(), getPos());
  }

  public void apply(Switch sw) {
    ((Analysis) sw).caseTBlockStart(this);
  }

  public void setText(String text) {
    throw new RuntimeException("Cannot change TBlockStart text.");
  }
}
