/* This file was generated by SableCC (http://www.sablecc.org/). */

package fr.umlv.symphonie.data.formula.node;

import fr.umlv.symphonie.data.formula.analysis.Analysis;

public final class TDivisionOperator extends Token {

  public TDivisionOperator() {
    super.setText("/");
  }

  public TDivisionOperator(int line, int pos) {
    super.setText("/");
    setLine(line);
    setPos(pos);
  }

  public Object clone() {
    return new TDivisionOperator(getLine(), getPos());
  }

  public void apply(Switch sw) {
    ((Analysis) sw).caseTDivisionOperator(this);
  }

  public void setText(String text) {
    throw new RuntimeException("Cannot change TDivisionOperator text.");
  }
}
