/* This file was generated by SableCC (http://www.sablecc.org/). */

package fr.umlv.symphonie.data.formula.node;

import fr.umlv.symphonie.data.formula.analysis.Analysis;

public final class TGreaterThanOrEquals extends Token {

  public TGreaterThanOrEquals() {
    super.setText(">=");
  }

  public TGreaterThanOrEquals(int line, int pos) {
    super.setText(">=");
    setLine(line);
    setPos(pos);
  }

  public Object clone() {
    return new TGreaterThanOrEquals(getLine(), getPos());
  }

  public void apply(Switch sw) {
    ((Analysis) sw).caseTGreaterThanOrEquals(this);
  }

  public void setText(String text) {
    throw new RuntimeException("Cannot change TGreaterThanOrEquals text.");
  }
}
