/* This file was generated by SableCC (http://www.sablecc.org/). */

package fr.umlv.symphonie.data.formula.node;

import fr.umlv.symphonie.data.formula.analysis.Analysis;

public final class TLessThanOrEquals extends Token {

  public TLessThanOrEquals() {
    super.setText("<=");
  }

  public TLessThanOrEquals(int line, int pos) {
    super.setText("<=");
    setLine(line);
    setPos(pos);
  }

  public Object clone() {
    return new TLessThanOrEquals(getLine(), getPos());
  }

  public void apply(Switch sw) {
    ((Analysis) sw).caseTLessThanOrEquals(this);
  }

  public void setText(String text) {
    throw new RuntimeException("Cannot change TLessThanOrEquals text.");
  }
}
