/* This file was generated by SableCC (http://www.sablecc.org/). */

package fr.umlv.symphonie.data.formula.node;

import fr.umlv.symphonie.data.formula.analysis.Analysis;

public final class TLessThan extends Token {

  public TLessThan() {
    super.setText("<");
  }

  public TLessThan(int line, int pos) {
    super.setText("<");
    setLine(line);
    setPos(pos);
  }

  public Object clone() {
    return new TLessThan(getLine(), getPos());
  }

  public void apply(Switch sw) {
    ((Analysis) sw).caseTLessThan(this);
  }

  public void setText(String text) {
    throw new RuntimeException("Cannot change TLessThan text.");
  }
}
