/* This file was generated by SableCC (http://www.sablecc.org/). */

package fr.umlv.symphonie.data.formula.node;

import fr.umlv.symphonie.data.formula.analysis.Analysis;

public final class TLogicalOrOperator extends Token {

  public TLogicalOrOperator() {
    super.setText("||");
  }

  public TLogicalOrOperator(int line, int pos) {
    super.setText("||");
    setLine(line);
    setPos(pos);
  }

  public Object clone() {
    return new TLogicalOrOperator(getLine(), getPos());
  }

  public void apply(Switch sw) {
    ((Analysis) sw).caseTLogicalOrOperator(this);
  }

  public void setText(String text) {
    throw new RuntimeException("Cannot change TLogicalOrOperator text.");
  }
}
