/* This file was generated by SableCC (http://www.sablecc.org/). */

package fr.umlv.symphonie.data.formula.node;

import fr.umlv.symphonie.data.formula.analysis.Analysis;

public final class TModulusOperator extends Token {

  public TModulusOperator() {
    super.setText("%");
  }

  public TModulusOperator(int line, int pos) {
    super.setText("%");
    setLine(line);
    setPos(pos);
  }

  public Object clone() {
    return new TModulusOperator(getLine(), getPos());
  }

  public void apply(Switch sw) {
    ((Analysis) sw).caseTModulusOperator(this);
  }

  public void setText(String text) {
    throw new RuntimeException("Cannot change TModulusOperator text.");
  }
}
