/* This file was generated by SableCC (http://www.sablecc.org/). */

package fr.umlv.symphonie.data.formula.node;

import fr.umlv.symphonie.data.formula.analysis.Analysis;

public final class TMultiplicationOperator extends Token {

  public TMultiplicationOperator() {
    super.setText("*");
  }

  public TMultiplicationOperator(int line, int pos) {
    super.setText("*");
    setLine(line);
    setPos(pos);
  }

  public Object clone() {
    return new TMultiplicationOperator(getLine(), getPos());
  }

  public void apply(Switch sw) {
    ((Analysis) sw).caseTMultiplicationOperator(this);
  }

  public void setText(String text) {
    throw new RuntimeException("Cannot change TMultiplicationOperator text.");
  }
}
