/* This file was generated by SableCC (http://www.sablecc.org/). */

package fr.umlv.symphonie.data.formula.node;

import fr.umlv.symphonie.data.formula.analysis.Analysis;

public final class TNotEquals extends Token {

  public TNotEquals() {
    super.setText("!=");
  }

  public TNotEquals(int line, int pos) {
    super.setText("!=");
    setLine(line);
    setPos(pos);
  }

  public Object clone() {
    return new TNotEquals(getLine(), getPos());
  }

  public void apply(Switch sw) {
    ((Analysis) sw).caseTNotEquals(this);
  }

  public void setText(String text) {
    throw new RuntimeException("Cannot change TNotEquals text.");
  }
}
