/* This file was generated by SableCC (http://www.sablecc.org/). */

package fr.umlv.symphonie.data.formula.node;

import fr.umlv.symphonie.data.formula.analysis.Analysis;

public final class TRightParenthesis extends Token {

  public TRightParenthesis() {
    super.setText(")");
  }

  public TRightParenthesis(int line, int pos) {
    super.setText(")");
    setLine(line);
    setPos(pos);
  }

  public Object clone() {
    return new TRightParenthesis(getLine(), getPos());
  }

  public void apply(Switch sw) {
    ((Analysis) sw).caseTRightParenthesis(this);
  }

  public void setText(String text) {
    throw new RuntimeException("Cannot change TRightParenthesis text.");
  }
}
