/* This file was generated by SableCC (http://www.sablecc.org/). */

package fr.umlv.symphonie.data.formula.node;

import fr.umlv.symphonie.data.formula.analysis.Analysis;

public final class TSubstractionOperator extends Token {

  public TSubstractionOperator() {
    super.setText("-");
  }

  public TSubstractionOperator(int line, int pos) {
    super.setText("-");
    setLine(line);
    setPos(pos);
  }

  public Object clone() {
    return new TSubstractionOperator(getLine(), getPos());
  }

  public void apply(Switch sw) {
    ((Analysis) sw).caseTSubstractionOperator(this);
  }

  public void setText(String text) {
    throw new RuntimeException("Cannot change TSubstractionOperator text.");
  }
}
