/* This file was generated by SableCC (http://www.sablecc.org/). */

package fr.umlv.symphonie.data.formula.node;

public final class X1PSeparatorSuffixedId extends XPSeparatorSuffixedId {

  private XPSeparatorSuffixedId _xPSeparatorSuffixedId_;
  private PSeparatorSuffixedId _pSeparatorSuffixedId_;

  public X1PSeparatorSuffixedId() {
  }

  public X1PSeparatorSuffixedId(XPSeparatorSuffixedId _xPSeparatorSuffixedId_,
      PSeparatorSuffixedId _pSeparatorSuffixedId_) {
    setXPSeparatorSuffixedId(_xPSeparatorSuffixedId_);
    setPSeparatorSuffixedId(_pSeparatorSuffixedId_);
  }

  public Object clone() {
    throw new RuntimeException("Unsupported Operation");
  }

  public void apply(Switch sw) {
    throw new RuntimeException("Switch not supported.");
  }

  public XPSeparatorSuffixedId getXPSeparatorSuffixedId() {
    return _xPSeparatorSuffixedId_;
  }

  public void setXPSeparatorSuffixedId(XPSeparatorSuffixedId node) {
    if (_xPSeparatorSuffixedId_ != null) {
      _xPSeparatorSuffixedId_.parent(null);
    }

    if (node != null) {
      if (node.parent() != null) {
        node.parent().removeChild(node);
      }

      node.parent(this);
    }

    _xPSeparatorSuffixedId_ = node;
  }

  public PSeparatorSuffixedId getPSeparatorSuffixedId() {
    return _pSeparatorSuffixedId_;
  }

  public void setPSeparatorSuffixedId(PSeparatorSuffixedId node) {
    if (_pSeparatorSuffixedId_ != null) {
      _pSeparatorSuffixedId_.parent(null);
    }

    if (node != null) {
      if (node.parent() != null) {
        node.parent().removeChild(node);
      }

      node.parent(this);
    }

    _pSeparatorSuffixedId_ = node;
  }

  void removeChild(Node child) {
    if (_xPSeparatorSuffixedId_ == child) {
      _xPSeparatorSuffixedId_ = null;
    }

    if (_pSeparatorSuffixedId_ == child) {
      _pSeparatorSuffixedId_ = null;
    }
  }

  void replaceChild(Node oldChild, Node newChild) {
  }

  public String toString() {
    return "" + toString(_xPSeparatorSuffixedId_)
        + toString(_pSeparatorSuffixedId_);
  }
}
